import { FieldConfig } from "@/components/AddModal";
import { DatePairConfig } from "@/lib/utils";

export const vehicleFields: FieldConfig[] = [
  {
    id: "plate_number",
    label: "차량 번호",
    placeholder: "1234, 12가1234, 기타",
    type: "text",
    isInput: true,
    isSelect: false,
    required: true,
  },
  {
    id: "vehicle_type",
    label: "차량 종류",
    placeholder: "차량 종류",
    type: "text",
    isInput: true,
    isSelect: true,
    required: false,
  },
  {
    id: "is_public_vehicle",
    label: "공용 차량",
    placeholder: "공용 차량 여부를 선택하세요",
    type: "boolean",
    isInput: false,
    isSelect: true,
    options: [
      { value: "true", label: "공용 차량" },
      { value: "false", label: "개인 차량" },
    ],
    required: false,
    defaultValue: "false",
  },
  {
    id: "owner_department",
    label: "공용 부서",
    placeholder: "공용 부서",
    type: "text",
    isInput: true,
    isSelect: false,
    required: false,
  },
  {
    id: "access_start_date",
    label: "접근 시작일",
    placeholder: "접근 시작일을 입력하세요",
    type: "date",
    isInput: true,
    isSelect: false,
    required: false,
    datePair: {
      startDateField: "access_start_date",
      endDateField: "access_end_date",
    } as DatePairConfig,
  },
  {
    id: "access_end_date",
    label: "접근 종료일",
    placeholder: "접근 종료일을 입력하세요",
    type: "date",
    isInput: true,
    isSelect: false,
    required: false,
    datePair: {
      startDateField: "access_start_date",
      endDateField: "access_end_date",
    } as DatePairConfig,
  },
  {
    id: "is_free_pass_enabled",
    label: "프리패스",
    placeholder: "프리패스 여부",
    type: "boolean",
    isInput: false,
    isSelect: true,
    options: [
      { value: "true", label: "프리패스 O" },
      { value: "false", label: "프리패스 X" },
    ],
    required: false,
    defaultValue: "false",
  },
  {
    id: "special_notes",
    label: "특이사항",
    placeholder: "특이사항",
    type: "text",
    isInput: true,
    isSelect: false,
    required: false,
  },
  {
    id: "status",
    label: "상태",
    placeholder: "상태를 선택하세요",
    type: "text",
    isInput: false,
    isSelect: true,
    required: false,
    options: [
      { value: "active", label: "활성" },
      { value: "inactive", label: "비활성" },
      { value: "blocked", label: "차단" },
    ],
    defaultValue: "active",
  },
  {
    id: "photo_path",
    label: "사진",
    placeholder: "사진을 선택하세요",
    type: "file",
    isInput: false,
    isSelect: false,
    required: false,
  },
];
